### ISSUE TITLE
How can i use your network

### ISSUE THREAD

**Issue by Liron-2** [GeneralLi95/deepglobe_land_cover_classification_with_deeplabv3plus#2]
hi, 
how can i use your network with my dataset? 
and how can i get the dataset that you work with? 

thank you! good luck!

**Comment by GeneralLi95** [comment]
Hi @Liron-2, this work is not finished yet. You may find some thing useful in this [repo](https://github.com/rishizek/tensorflow-deeplab-v3-plus) .  Good luck.

**Comment by jewhau** [comment]
你好， 请问下你知道用什么软件能标注（lable）遥感影像语义分割数据集吗？

**Comment by jewhau** [comment]
> @Liron-2 You can see this repo [labelme](https://github.com/wkentaro/labelme)

labelme处理不了太大的遥感影像吧

**Comment by GeneralLi95** [comment]
@jewhau ArcGIS

**Comment by jewhau** [comment]
> @jewhau ArcGIS

刚才问了别人，说可以用qgis，非常感谢你的回答

**Comment by GeneralLi95** [comment]
@jewhau QGIS 轻便一些，比ArcGIS好上手许多

**Comment by jewhau** [comment]
> @jewhau QGIS 轻便一些，比ArcGIS好上手许多

好的，谢谢

**Comment by RustSon** [comment]
hi,
would you like to give me the trained model to try this demo?
I very want to see the result .Thanks a lot!

**Comment by Wenya0210** [comment]
你好，我刚开始做遥感图像方面的语义分割，看到了您做的deepglobe land cover classification的工作,我也想尝试实现一下。看了您上传的代码，代码和用途匹配不起来，您能大概介绍下每一个代码是实现什么的吗
非常感谢！

**Comment by RustSon** [comment]
他这个项目应该还没完成，我之前也跑过，没跑起来，你要是不嫌麻烦，可以自己做数据集，用deeplabv3+训练，效果也不错


发自网易邮箱 iPhone 版
在2019年07月17日 00:14，wenya 写道:

你好，我刚开始做遥感图像方面的语义分割，看到了您做的deepglobe land cover classification的工作,我也想尝试实现一下。看了您上传的代码，代码和用途匹配不起来，您能大概介绍下每一个代码是实现什么的吗
非常感谢！

**Comment by Wenya0210** [comment]
好的，谢谢


发自我的iPhone

------------------ Original ------------------

**Comment by GeneralLi95** [comment]
> 他这个项目应该还没完成，我之前也跑过，没跑起来，你要是不嫌麻烦，可以自己做数据集，用deeplabv3+训练，效果也不错 发自网易邮箱 iPhone 版 在2019年07月17日 00:14，wenya 写道: 你好，我刚开始做遥感图像方面的语义分割，看到了您做的deepglobe land cover classification的工作,我也想尝试实现一下。看了您上传的代码，代码和用途匹配不起来，您能大概介绍下每一个代码是实现什么的吗 非常感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

@jewhau @Wenya0210 主要代码已经完成了，因为前段时间忙别的一些事情有半年没太更新过了。最近在完善一篇论文，等十一月下旬左右应该会重新把这个repo再理一下。

**Comment by Wenya0210** [comment]
好的



发自我的iPhone


------------------ Original ------------------
