### ISSUE TITLE
Help for val dataset and corresponding label files

### ISSUE THREAD

**Issue by Lelouch-Ice** [GeneralLi95/deepglobe_land_cover_classification_with_deeplabv3plus#3]
Hello, good work! But I only found the train set in the link you provided, do you have the val dataset and corresponding label files for the val dataset that is provided by the DeepGlobe website?  
I couldn't participate in the competition as the time is kind of late now and I can't access the dataset

**Comment by GeneralLi95** [comment]
> Hello, good work! But I only found the train set in the link you provided, do you have the val dataset and corresponding label files for the val dataset that is provided by the DeepGlobe website?
> I couldn't participate in the competition as the time is kind of late now and I can't access the dataset

Sorry, I don't have the copyright of this dataset, so I can't give you without permission. You can still do the job no matter the competition is over or not. The website is still open. Thank you.
