### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by ilkedemir** [GeneralLi95/deepglobe_land_cover_classification_with_deeplabv3plus#5]
Distributing DeepGlobe datasets on any platform other than Codalab is not permitted by policy. Please remove the baidu link from your intro. Also, using DeepGlobe requires referring to the original source, you should cite the [paper](http://openaccess.thecvf.com/content_cvpr_2018_workshops/w4/html/Demir_DeepGlobe_2018_A_CVPR_2018_paper.html) and optionally refer to the [website](http://deepglobe.org/).

**Comment by GeneralLi95** [comment]
Sorry, I didn't notice that. I will remove it now.

**Comment by GeneralLi95** [comment]
@ilkedemir 
Sorry, I didn't notice that. I will remove it now.

**Comment by GeneralLi95** [comment]
@ilkedemir  It was removed now.
