### ISSUE TITLE
Would you please share the dataset?

### ISSUE THREAD

**Issue by lucy609** [GeneralLi95/deepglobe_land_cover_classification_with_deeplabv3plus#6]
Hello,I try to get the dataset in the website, but told 'Your request to participate in this challenge has been received and a decision is pending.'.
And  I try to  leave a message in 'Forums' but still could not get it.
Would you please share the dataset to us ?Maybe in a link ? Thanks a lot!
Look forward to your  favourable reply.

**Comment by GeneralLi95** [comment]
@lucy609  Thank you. Due to the copyright restrict, I can't share the dataset( I have been warned...). Sorry. I hope your request will be permitted soon.

**Comment by GeneralLi95** [comment]
@lucy609  You can E-mail to me if you have any other qustions

**Comment by lucy609** [comment]
Thank you for your patient replies.
