### ISSUE TITLE
Dateset Requeset

### ISSUE THREAD

**Issue by bobp26** [GeneralLi95/deepglobe_land_cover_classification_with_deeplabv3plus#7]
hello, do you have a dataset for the deepglobe_land_cover_classification competition?Could you  share the baidu cloud or Google cloud link, thank you very much

**Comment by GeneralLi95** [comment]
@pengzhou926 Thank you .
 Due to the copyright restriction , I can't  share the dataset. I have been warned by the owner. While the competition can still be registered. So you can still get the dataset by that way.

**Comment by code-wizard-code** [comment]
Hello, I’m a master’s student and I’ve read your paper and i liked it, can you give us entrained modèm,  we need to do some comparisons

**Comment by KunalChaturvedi28** [comment]
Someone has shared at [https://www.kaggle.com/balraj98/deepglobe-land-cover-classification-dataset](https://www.kaggle.com/balraj98/deepglobe-land-cover-classification-dataset). I am not sure if the author of this link has the copyright to upload.

**Comment by GeneralLi95** [comment]
@KunalChaturvedi28 I don't know either.
